---
title: "RMarkDown for Reproducible Research Week 2 Assignment"
author: "N Gopal Krishna Sharma"
date: "March 19, 2017"
output: html_document
keep_md: TRUE
---


## Loading and preprocessing the data
```{r}
data <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r}
formattedDates<-as.Date(data$date,format="%m%d%Y")
total_steps <- tapply(data$steps, data$date, FUN=sum, na.rm=TRUE)
hist(total_steps,main="Total Steps Each day",xlab = "Date (no of days since 1970 1 Jan)", ylab = "Steps")
mean(total_steps,na.rm = TRUE)
median(total_steps,na.rm = TRUE)
```

## What is the average daily activity pattern?
```{r}
library(ggplot2)
averages <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval),
                      FUN=mean, na.rm=TRUE)
ggplot(data=averages, aes(x=interval, y=steps)) +
    geom_line() +
    xlab("Interval") +
    ylab("Average number of steps taken")
averages[which.max(averages$steps),]
```

##Imputing missing values
```{r}
missing <- is.na(data$steps)
fill_value <- function(steps, interval) {
    filled <- NA
    if (!is.na(steps))
        filled <- c(steps)
    else
        filled <- (averages[averages$interval==interval, "steps"])
    return(filled)
}
filled_data <- data
filled_data$steps <- mapply(fill_value, filled_data$steps, filled_data$interval)
total_steps <- tapply(filled_data$steps, filled_data$date, FUN=sum)
hist(total_steps,main="Total Steps Each day",xlab = "Date (no of days since 1970 1 Jan)", ylab = "Steps")
```

##Are there differences in activity patterns between weekdays and weekends?
```{r}
weekday_or_weekend <- function(date) {
    day <- weekdays(date)
    if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
        return("weekday")
    else if (day %in% c("Saturday", "Sunday"))
        return("weekend")
    else
        stop("invalid date")
}
filled_data$date <- as.Date(filled_data$date)
filled_data$day <- sapply(filled_data$date, FUN=weekday_or_weekend)
averages <- aggregate(steps ~ interval + day, data=filled_data, mean)
ggplot(averages, aes(interval, steps)) + geom_line() + facet_grid(day ~ .) +
    xlab("5-minute interval") + ylab("Number of steps")
```